Update README.md
Using that syntax throws me this error:

```
ERROR: `https://github.com/CliMA/LESbrary.jl.git` is not a valid package name
The argument appears to be a URL or path, perhaps you meant `Pkg.add(url="...")` or `Pkg.add(path="...")`.
```

I'm assuming there was a change in a recent Julia version. The updated syntax appears to work (I'm using Julia version 1.5.2 by the way).